# Generated by Django 4.2.1 on 2023-05-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_newssource_subscribers_page_news_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publishedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
